
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb", "80000"]

-   repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
    - id: isort
      types: [python]
      args: ["--profile", "black"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.2.3
    hooks:
    -   id: pydocstyle
        types: [python]
        args: ["--convention", "google", "--add-ignore", "D301,D105"]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        types: [python]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
    -   id: nbqa-isort
        args: ["--profile=black"]
    -   id: nbqa-black
    -   id: nbqa-mypy
        types: [jupyter]
    -   id: nbqa-flake8
        args: ["--config=.flake8", "--extend-ignore=E402"]

-   repo: https://github.com/MarcoGorelli/check-execution-order
    rev: v0.1.1
    hooks:
    -   id: check-execution-order
