name: visualizing-mcmc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - arviz
  - jupyterlab
  - jupyterlab_code_formatter
  - jupyterlab-spellchecker
  - matplotlib
  - mypy
  - nbconvert
  - nbformat
  - nbqa
  - numpy
  - pandas
  - pip
  - pymc>=4
  - scikit-misc
  - seaborn
  - watermark
  - pip:
    - pre-commit
    - black
    - isort
    - mypy
    - flake8
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
